networks:
  app_network:
    driver: bridge
    external: false

services:
  forum_postgres:
    image: postgres:16-alpine
    container_name: forum_postgres_container
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-forum_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-forum_pass}
      POSTGRES_DB: ${POSTGRES_DB:-forum_db}
    volumes:
      - forum_postgres_volume:/var/lib/postgresql/data
    networks:
      - app_network

  forum_keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: forum_keycloak_container
    restart: always
    command: 
      - start-dev
      - "--import-realm"
      - "--health-enabled=true"
    ports:
      - "${KEYCLOAK_PORT:-5000}:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-forum}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-frontend-app}
    volumes:
      - forum_keycloak_volume:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    entrypoint: ["/opt/keycloak/bin/kc.sh"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'exec 3<>/dev/tcp/localhost/8080; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  forum_backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        PORT: "8080"
    container_name: forum_backend_container
    restart: always
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      API_HOST: "0.0.0.0"
      API_PORT: "${API_PORT:-8080}"

      CORS_ORIGINS: "${CORS_ORIGINS:-*}"

      POSTGRES_HOST: "forum_postgres"
      POSTGRES_PORT: "${POSTGRES_PORT:-5432}"
      POSTGRES_USER: "${POSTGRES_USER:-forum_user}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-forum_pass}
      POSTGRES_DB: ${POSTGRES_DB:-forum_db}

      KEYCLOAK_HOST: "forum_keycloak"
      KEYCLOAK_PORT: "8080"
      KEYCLOAK_URL: "forum_keycloak:8080,${KEYCLOAK_HOST:-localhost}:${KEYCLOAK_PORT:-5000}"
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-forum}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-frontend-app}
    depends_on:
      forum_postgres:
        condition: service_started
      forum_keycloak:
        condition: service_healthy
    networks:
      - app_network

  forum_frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        KEYCLOAK_URL: "${KEYCLOAK_URL:-http://localhost:5000}"
        KEYCLOAK_REALM: ${KEYCLOAK_REALM:-forum}
        KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-frontend-app}
        API_URL: "${API_URL:-http://localhost:8080/api}"
    container_name: forum_frontend_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      forum_backend:
        condition: service_started
    networks:
      - app_network

volumes:
  forum_postgres_volume:
  forum_keycloak_volume:
