apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: forum-backend:local
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: forum-config
        - secretRef:
            name: forum-secret
        env:
        - name: KEYCLOAK_URL
          value: "keycloak:8080"
        - name: API_HOST
          value: "0.0.0.0"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
  selector:
    app: backend
