apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        command: ["/opt/keycloak/start.sh"]
        args: ["start-dev", "--import-realm", "--health-enabled=true"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: forum-secret
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: forum-config
              key: KEYCLOAK_REALM
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: forum-config
              key: KEYCLOAK_CLIENT_ID
        volumeMounts:
        - name: data
          mountPath: /opt/keycloak/data
        - name: config
          mountPath: /opt/keycloak/data/import/realm-export.json
          subPath: realm-export.json
        - name: config
          mountPath: /opt/keycloak/start.sh
          subPath: start.sh
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: keycloak-pvc
      - name: config
        configMap:
          name: keycloak-config
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: keycloak
